import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ordersApi } from '../api/ordersApi';
import { settingsApi } from '../api/settingsApi';

const PaymentPage = () => {
  const { id } = useParams(); const [order, setOrder] = useState(null); const [bank, setBank] = useState(null); const [error, setError] = useState(''); const [momoLoading, setMomoLoading] = useState(false);
  useEffect(() => { Promise.all([ordersApi.getOrderById(id), settingsApi.getBank()]).then(([currentOrder, currentBank]) => { setOrder(currentOrder); setBank(currentBank); }).catch(() => setError('Không tải được thông tin thanh toán.')); }, [id]);
  const payMomo = async () => { setMomoLoading(true); setError(''); try { const result = await ordersApi.startMomoPayment(id); window.location.assign(result.payUrl); } catch { setError('Không thể kết nối MoMo. Hãy thử lại hoặc chọn chuyển khoản ngân hàng.'); setMomoLoading(false); } };
  const copy = (value) => navigator.clipboard?.writeText(value);
  if (error && !order) return <div className="page"><div className="alert alert-error">{error}</div></div>;
  if (!order) return <div className="page"><p className="muted">Đang tải thông tin thanh toán...</p></div>;
  const configured = bank?.bank_bin && bank?.account_number; const content = `DH${order.id}`; const qrUrl = configured ? `https://img.vietqr.io/image/${bank.bank_bin}-${bank.account_number}-compact2.png?amount=${Math.round(order.total_amount)}&addInfo=${content}&accountName=${encodeURIComponent(bank.account_name || '')}` : null;
  return <div className="page payment-page"><div className="payment-heading"><span className="eyebrow">THANH TOÁN AN TOÀN</span><h2 className="section-title">Thanh toán đơn hàng #{order.id}</h2><p className="section-sub">Tổng thanh toán: <b>{order.total_amount.toLocaleString('vi-VN')} đ</b></p></div><div className="payment-layout"><section className="card card-pad payment-details"><div className="payment-step">Quét QR MoMo</div><h3 style={{ marginTop: 0 }}>Thanh toán với MoMo</h3><p className="muted text-sm">Mở ứng dụng MoMo hoặc ứng dụng ngân hàng, quét mã bên dưới và chuyển đúng số tiền của đơn hàng.</p><div className="momo-qr-frame"><img src="/momo-payment-qr.jpg" alt="Mã QR nhận tiền MoMo" /></div><p className="text-sm muted">Sau khi chuyển khoản, cửa hàng sẽ kiểm tra và xác nhận đơn hàng.</p>{error && <div className="alert alert-error">{error}</div>}<button type="button" onClick={payMomo} disabled={momoLoading} className="btn momo-button btn-block">{momoLoading ? 'Đang kết nối MoMo...' : 'Thanh toán MoMo online (Sandbox)'}</button></section><section className="card card-pad payment-qr-card"><div className="payment-step">Hoặc chuyển khoản VietQR</div>{configured ? <><div className="qr-frame"><img src={qrUrl} alt="Mã thanh toán VietQR" /></div><div className="transfer-details" style={{ width: '100%', marginTop: 14 }}><div className="transfer-row"><span>Ngân hàng</span><strong>{bank.bank_name}</strong></div><div className="transfer-row"><span>Số tài khoản</span><strong>{bank.account_number} <button className="copy-button" onClick={() => copy(bank.account_number)}>Sao chép</button></strong></div><div className="transfer-row"><span>Nội dung</span><strong>{content} <button className="copy-button" onClick={() => copy(content)}>Sao chép</button></strong></div></div></> : <div className="alert alert-info">Cửa hàng chưa cấu hình tài khoản ngân hàng.</div>}</section></div><div className="payment-actions" style={{ maxWidth: 500, margin: '20px auto 0' }}><Link to={`/orders/${order.id}`} className="btn btn-primary btn-block">Theo dõi đơn hàng</Link><Link to="/books" className="btn btn-outline btn-block">Tiếp tục mua sắm</Link></div></div>;
};
export default PaymentPage;
