import { useEffect, useState } from 'react';
import { customersApi } from '../api/customersApi';
import { getApiErrorMessage } from '../api/errorHandler';

const AdminCustomersPage = () => {
  const [customers, setCustomers] = useState([]); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); setError(''); customersApi.getAll().then(setCustomers).catch((e) => setError(getApiErrorMessage(e, 'Không tải được dữ liệu khách hàng.'))).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const updated = await customersApi.update(editing.id, editing); setCustomers((items) => items.map((item) => item.id === updated.id ? updated : item)); setEditing(null); } catch (e) { setError(getApiErrorMessage(e, 'Không thể lưu thông tin khách hàng.')); } finally { setSaving(false); } };
  return <div className="page"><h2 className="section-title">Thông tin khách hàng</h2><p className="section-sub">Chỉ quản trị viên được xem và chỉnh sửa dữ liệu này.</p>{error && <div className="alert alert-error">{error}</div>}{loading ? <div className="empty-state">Đang tải khách hàng...</div> : customers.length === 0 ? <div className="empty-state">Chưa có khách hàng.</div> : <div className="card"><table className="table"><thead><tr><th>Khách hàng</th><th>Email</th><th>Số điện thoại</th><th>Địa chỉ</th><th></th></tr></thead><tbody>{customers.map((c) => <tr key={c.id}><td>{c.full_name}</td><td>{c.email}</td><td>{c.phone || '—'}</td><td>{c.address || '—'}</td><td><button className="btn btn-outline btn-sm" onClick={() => setEditing({ ...c })}>Chỉnh sửa</button></td></tr>)}</tbody></table></div>}{editing && <div className="modal-backdrop"><form className="card card-pad customer-form" onSubmit={save}><h3>Chỉnh sửa khách hàng</h3>{[['full_name','Họ tên'],['email','Email'],['phone','Số điện thoại'],['address','Địa chỉ']].map(([name,label]) => <div className="field" key={name}><label>{label}</label><input className="input" type={name === 'email' ? 'email' : 'text'} value={editing[name] || ''} onChange={(e) => setEditing({ ...editing, [name]: e.target.value })} required /></div>)}<div className="modal-actions"><button type="button" className="btn btn-outline" onClick={() => setEditing(null)}>Hủy</button><button disabled={saving} className="btn btn-primary">{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</button></div></form></div>}</div>;
};
export default AdminCustomersPage;
