import { useEffect, useState } from 'react';
import { commerceApi } from '../api/commerceApi';
import { getApiErrorMessage } from '../api/errorHandler';

const empty = { code: '', percent_off: 10, min_order_amount: 0, max_uses: '', expires_at: '' };
export default function AdminCouponsPage() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(null); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); setError(''); commerceApi.coupons().then(setItems).catch((e) => setError(getApiErrorMessage(e, 'Không tải được mã khuyến mãi.'))).finally(() => setLoading(false)); };
  useEffect(load, []);
  const create = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, code: form.code.trim().toUpperCase(), percent_off: Number(form.percent_off), min_order_amount: Number(form.min_order_amount), max_uses: form.max_uses ? Number(form.max_uses) : null, expires_at: form.expires_at ? new Date(`${form.expires_at}T23:59:59`).toISOString() : null }; const coupon = await commerceApi.createCoupon(payload); setItems((old) => [coupon, ...old]); setForm(null); } catch (e2) { setError(getApiErrorMessage(e2, 'Không thể tạo mã khuyến mãi.')); } finally { setSaving(false); } };
  const toggle = async (coupon) => { try { const updated = await commerceApi.setCouponActive(coupon.id, !coupon.is_active); setItems((old) => old.map((x) => x.id === coupon.id ? { ...x, ...updated } : x)); } catch (e) { setError(getApiErrorMessage(e, 'Không thể cập nhật trạng thái mã.')); } };
  const date = (value) => value ? new Date(value).toLocaleDateString('vi-VN') : 'Không giới hạn';
  return <div className="page"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}><div><h2 className="section-title">Khuyến mãi</h2><p className="section-sub">Tạo và kiểm soát mã giảm giá cho đơn hàng.</p></div><button className="btn btn-primary" onClick={() => setForm({ ...empty })}>+ Tạo mã</button></div>{error && <div className="alert alert-error">{error} <button onClick={load}>Thử lại</button></div>}{loading ? <div className="empty-state">Đang tải mã khuyến mãi...</div> : !items.length ? <div className="empty-state">Chưa có mã khuyến mãi nào.</div> : <div className="card"><table className="table"><thead><tr><th>Mã</th><th>Giảm</th><th>Đơn tối thiểu</th><th>Lượt dùng</th><th>Hết hạn</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map((c) => <tr key={c.id}><td><strong>{c.code}</strong></td><td>{c.percent_off}%</td><td>{c.min_order_amount.toLocaleString('vi-VN')} đ</td><td>{c.used_count}{c.max_uses ? ` / ${c.max_uses}` : ' / ∞'}</td><td>{date(c.expires_at)}</td><td>{c.is_active ? 'Đang bật' : 'Đã tắt'}</td><td><button className={`btn btn-sm ${c.is_active ? 'btn-outline' : 'btn-primary'}`} onClick={() => toggle(c)}>{c.is_active ? 'Tắt mã' : 'Bật mã'}</button></td></tr>)}</tbody></table></div>}{form && <div className="modal-backdrop"><form className="card card-pad customer-form" onSubmit={create}><h3>Tạo mã khuyến mãi</h3><div className="field"><label>Mã code</label><input className="input" required minLength="3" maxLength="50" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="VIETBOOK10" /></div><div className="field"><label>Phần trăm giảm</label><input className="input" type="number" required min="1" max="100" value={form.percent_off} onChange={(e) => setForm({ ...form, percent_off: e.target.value })} /></div><div className="field"><label>Giá trị đơn tối thiểu</label><input className="input" type="number" min="0" value={form.min_order_amount} onChange={(e) => setForm({ ...form, min_order_amount: e.target.value })} /></div><div className="field"><label>Giới hạn lượt dùng (không bắt buộc)</label><input className="input" type="number" min="1" value={form.max_uses} onChange={(e) => setForm({ ...form, max_uses: e.target.value })} /></div><div className="field"><label>Ngày hết hạn (không bắt buộc)</label><input className="input" type="date" value={form.expires_at} onChange={(e) => setForm({ ...form, expires_at: e.target.value })} /></div><div className="modal-actions"><button type="button" className="btn btn-outline" onClick={() => setForm(null)}>Hủy</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Đang tạo...' : 'Tạo mã'}</button></div></form></div>}</div>;
}
