import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ordersApi } from '../api/ordersApi';
import { customersApi } from '../api/customersApi';
import { useAuth } from '../auth/useAuth';
import StatusBadge from '../components/StatusBadge';
import { getApiErrorMessage } from '../api/errorHandler';
const STATUS = ['PENDING_PAYMENT', 'COD_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELED'];
export default function OrderDetailPage() {
  const { id } = useParams(); const { role } = useAuth(); const isAdmin = role === 'ADMIN';
  const [order, setOrder] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false);
  const load = () => ordersApi.getOrderById(id).then(setOrder).catch((e) => setError(getApiErrorMessage(e, 'Không tải được chi tiết đơn hàng.'))).finally(() => setLoading(false));
  useEffect(load, [id]);
  const updateStatus = async (e) => { try { const updated = await ordersApi.updateStatus(order.id, e.target.value); setOrder({ ...updated, customer: order.customer }); } catch { setError('Cập nhật trạng thái thất bại.'); } };
  const save = async (e) => { e.preventDefault(); setSaving(true); try { const customer = await customersApi.update(editing.id, { ...editing, role: editing.role || 'CUSTOMER' }); setOrder({ ...order, customer }); setEditing(null); } catch (err) { setError(getApiErrorMessage(err, 'Không thể lưu thông tin khách hàng.')); } finally { setSaving(false); } };
  if (loading) return <div className="page"><p className="muted">Đang tải...</p></div>;
  if (!order) return <div className="page"><div className="alert alert-error">{error || 'Không tìm thấy đơn hàng.'}</div></div>;
  return <div className="page"><Link to={isAdmin ? '/admin/orders' : '/orders'} className="text-sm muted">← Quay lại danh sách đơn</Link><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap' }}><h2 className="section-title">Đơn hàng #{order.id}</h2>{isAdmin ? <select value={order.status} onChange={updateStatus} className="input" style={{ maxWidth: 220 }}>{STATUS.map((s) => <option key={s}>{s}</option>)}</select> : <StatusBadge status={order.status} />}</div>{error && <div className="alert alert-error">{error}</div>}{isAdmin && order.customer && <section className="card card-pad" style={{ marginBottom: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><h3>Thông tin khách hàng</h3><p><b>{order.customer.full_name}</b> · {order.customer.email}</p><p className="muted">{order.customer.phone || 'Chưa có SĐT'} · {order.customer.address || 'Chưa có địa chỉ'}</p></div><button className="btn btn-outline btn-sm" onClick={() => setEditing({ ...order.customer, role: 'CUSTOMER' })}>Chỉnh sửa khách hàng</button></div></section>}<section className="card card-pad"><strong>Thanh toán: {order.payment_method}</strong><p className="muted">Trạng thái: {order.payment_status} · Mã giao dịch: {order.transaction_code || '—'}</p>{order.coupon_code && <p className="text-sm" style={{ color: 'var(--color-primary)' }}>Ưu đãi: <b>{order.coupon_code}</b> · giảm {(order.discount_amount || 0).toLocaleString('vi-VN')} đ</p>}</section><div className="card" style={{ marginTop: 10 }}><table className="table"><thead><tr><th>Sách</th><th>Đơn giá</th><th>SL</th><th>Thành tiền</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td>{item.book_title}</td><td>{item.book_price.toLocaleString('vi-VN')} đ</td><td>{item.quantity}</td><td>{item.line_total.toLocaleString('vi-VN')} đ</td></tr>)}</tbody></table></div><p style={{ textAlign: 'right' }}>Tổng cộng: <strong>{order.total_amount.toLocaleString('vi-VN')} đ</strong></p>{editing && <div className="modal-backdrop"><form className="card card-pad customer-form" onSubmit={save}><h3>Chỉnh sửa khách hàng</h3>{[['full_name', 'Họ tên'], ['email', 'Email'], ['phone', 'Số điện thoại'], ['address', 'Địa chỉ']].map(([field, label]) => <div className="field" key={field}><label>{label}</label><input className="input" required type={field === 'email' ? 'email' : 'text'} value={editing[field] || ''} onChange={(e) => setEditing({ ...editing, [field]: e.target.value })} /></div>)}<div className="modal-actions"><button type="button" className="btn btn-outline" onClick={() => setEditing(null)}>Hủy</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</button></div></form></div>}</div>;
}
